[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.build]
cmds = ["npm install --prefix frontend", "npm run build --prefix frontend", "npm install --prefix backend"]

[start]
cmd = "node backend/server.js"
